name: Run Command Based on Environment Input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Enter a command (pwd or date)"
        required: true
        type: choice
        options:
          - pwd
          - date

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ./ansible/run_command.yml --extra-vars "environment=${{ inputs.environment }}"

